title: itenium
baseurl: "/blog"
image_base_url: https://itenium-be.github.io/blog-posts-new/assets
url: "https://itenium.be"
email: info@itenium.be

# Blog
github_data_url: https://github.com/itenium-be/blog-posts/blob/master
permalink: /:categories/:slug/

# Build settings
markdown: kramdown

kramdown:
  syntax_highlighter_opts:
    disable: true

# https://github.com/jekyll/minima
# bundle info minima
theme: minima

plugins:
  - jemoji
  - jekyll-gist
  - jekyll-avatar

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore
  - .editorconfig
  - .claude
  - vendor
  - .bundle
  - check-separators.ps1
  - deepen-headers.ps1
